name: sparknlp
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0=h3b92ee0_0
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38h0a891b7_1005
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - cffi=1.15.1=py38h4a40e3a_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.2=pyhd8ed1ab_0
  - cryptography=39.0.0=py38h3d167d9_0
  - debugpy=1.6.4=py38hfa26641_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=5.2.0=pyha770c72_0
  - importlib_resources=5.10.1=pyhd8ed1ab_1
  - ipykernel=6.19.4=pyh210e3f2_0
  - ipython=8.7.0=pyh41d4057_0
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=7.4.8=pyhd8ed1ab_0
  - jupyter_core=5.1.1=py38h578d9bd_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - libhwloc=2.8.0=h32351e8_1
  - libiconv=1.17=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=he0ac6c6_5
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.40.0=h753d276_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - llvmlite=0.39.1=py38h38d86a4_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - nbformat=5.7.1=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - numba=0.56.4=py38h9a4aae9_0
  - openssl=3.0.7=h0b41bf4_1
  - packaging=22.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=22.3.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=2.6.2=pyhd8ed1ab_0
  - plotly-orca=1.3.1=1
  - pooch=1.6.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.36=pyha770c72_0
  - psutil=5.9.4=py38h0a891b7_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pynndescent=0.5.8=pyh1a96a4e_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.15=h4a9ceb5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
  - python_abi=3.8=3_cp38
  - pyzmq=24.0.1=py38hfc09fa9_1
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - scikit-learn=1.2.0=py38h1e1a916_0
  - setuptools=65.6.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.7.0=h924138e_1
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h27826a3_0
  - tornado=6.2=py38h0a891b7_1
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.8.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - umap-learn=0.5.3=py38h578d9bd_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.38.4=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.11.0=pyhd8ed1ab_0
  - pip:
    - accessible-pygments==0.0.4
    - alabaster==0.7.13
    - babel==2.12.1
    - beautifulsoup4==4.11.1
    - certifi==2022.12.7
    - click==8.1.3
    - contourpy==1.0.6
    - cycler==0.11.0
    - dataclasses==0.6
    - docutils==0.18.1
    - fonttools==4.38.0
    - greenlet==2.0.2
    - imagesize==1.4.1
    - importlib-resources==5.10.2
    - jinja2==3.1.2
    - jupyter-book==0.15.1
    - jupyter-cache==0.5.0
    - kiwisolver==1.4.4
    - latexcodec==2.0.1
    - linkify-it-py==2.0.0
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.6.2
    - mdit-py-plugins==0.3.5
    - mdurl==0.1.2
    - myst-nb==0.17.1
    - myst-parser==0.18.1
    - nbclient==0.5.13
    - networkx==2.8.8
    - nltk==3.8
    - nlu==4.0.0
    - numpy==1.24.1
    - pandas==1.5.2
    - pillow==9.3.0
    - py4j==0.10.9.5
    - pybtex==0.24.0
    - pybtex-docutils==1.0.2
    - pydata-sphinx-theme==0.13.3
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - pyspark==3.2.3
    - pytz==2022.7
    - pyyaml==6.0
    - regex==2022.10.31
    - scipy==1.9.3
    - seaborn==0.12.2
    - session-info==1.0.0
    - snowballstemmer==2.2.0
    - soupsieve==2.3.2.post1
    - spark-nlp==4.0.2
    - sphinx==5.0.2
    - sphinx-book-theme==1.0.1
    - sphinx-comments==0.0.3
    - sphinx-copybutton==0.5.1
    - sphinx-design==0.3.0
    - sphinx-external-toc==0.3.1
    - sphinx-jupyterbook-latex==0.5.2
    - sphinx-multitoc-numbering==0.1.3
    - sphinx-thebe==0.2.1
    - sphinx-togglebutton==0.3.2
    - sphinxcontrib-applehelp==1.0.4
    - sphinxcontrib-bibtex==2.5.0
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.1
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - sqlalchemy==1.4.47
    - stdlib-list==0.8.0
    - tabulate==0.9.0
    - uc-micro-py==1.0.1
    - urllib3==1.26.13
